stages:
  - lint
  - test
  - build
  - security  
  - push
  - deploy

variables:
  # go
  GO_VERSION: "1.25.1"
  GOPATH: "${CI_PROJECT_DIR}/.cache/go-path"
  GOMODCACHE: "${CI_PROJECT_DIR}/.cache/go-mod"
  GOCACHE: "${CI_PROJECT_DIR}/.cache/go-build"
  # docker
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

default:
  image: golang:${GO_VERSION}-alpine
  cache:
    key:
      files:
        - go.sum
    paths:
      - ${GOPATH}
      - ${GOCACHE}

# LINT

lint:
  stage: lint
  before_script:
    - apk add --no-cache git
    - go install honnef.co/go/tools/cmd/staticcheck@latest
  script:
    - go mod tidy
    - go mod verify
    - go vet ./...
    - $(go env GOPATH)/bin/staticcheck ./...
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# TEST

test:
  stage: test
  services:
    - name: redis:6.2-alpine
      alias: redis
    - name: postgres:16-alpine
      alias: db
  variables:
    POSTGRES_NAME: gosocial-test
    POSTGRES_USER: test
    POSTGRES_PASSWORD: test
    DB_URL: "postgres://test:test@db:5432/gosocial-test?sslmode=disable"
  before_script:
    - apk add --no-cache git build-base
  script:
    - go build -v ./...
    - go test -race -vet=off -coverprofile=coverage.out ./...
    - go tool cover -func=coverage.out
  coverage: '/^total:\s+\(statements\)\s+(\d+\.\d+)%/'
  artifacts:
    when: always
    paths:
      - coverage.out
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    expire_in: 7 days
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      
govulncheck:
  stage: security
  image: golang:${GO_VERSION}-alpine
  before_script:
    - apk add --no-cache git
    - go install golang.org/x/vuln/cmd/govulncheck@latest
  script:
    - $(go env GOPATH)/bin/govulncheck ./...
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      
# BUILD

build-image:
  stage: build
  tags: 
   - docker-runner
  image: docker:24.0
  variables:
    DOCKER_HOST: "unix:///var/run/docker.sock"
    DOCKER_TLS_CERTDIR: ""
    IMAGE_TAG: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  script:
    - docker version
    - docker info
    - docker build -t "$IMAGE_TAG" -f docker/Dockerfile .
    - docker images | grep gosocial
    - docker save "$IMAGE_TAG" -o image.tar
  artifacts:
    paths: 
      - image.tar
    expire_in: 1 hour
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

trivy:
  stage: security
  tags:
    - docker-runner
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  needs:
    - build-image
  variables:
    DOCKER_HOST: "unix:///var/run/docker.sock"
    DOCKER_TLS_CERTDIR: ""
    IMAGE_TAG: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  before_script:
    - trivy --version
  script:
    - trivy image --input image.tar --severity CRITICAL --exit-code 1 --no-progress 
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      
# PUSH
 
push-image:
  stage: push
  tags:
    - docker-runner
  image: docker:24.0
  needs:
    - build-image
    - trivy
  variables:
    DOCKER_HOST: "unix:///var/run/docker.sock"
    DOCKER_TLS_CERTDIR: ""
    IMAGE_TAG: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  script:
    - docker load -i image.tar
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker push "$IMAGE_TAG"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
 
# DEPLOY
 
deploy-to-minikube:
  stage: deploy
  tags:
    - minikube-runner
  variables:
    CI_DEBUG_TRACE: "true"
    IMAGE_TAG: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"      
  script:
    - kubectl set image deployment/backend backend="$IMAGE_TAG"
    - kubectl rollout status deployment/backend --timeout=120s
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


