apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
type: Opaque
stringData:
    DB_USER: ENC[AES256_GCM,data:JxfaUfs=,iv:DkVFbW97A2DsSh/HI2cy1t4O5iK2gT9SY1Mrnk/2BaI=,tag:fzGRxFlTS4fzuPNL9mABxQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:sOJ9Xw6a,iv:Qgqx+jxc+y7rfZYFnce91e6VMtPka7mHjcY8h4fp+VY=,tag:ahY+wlLxGcyafoAc9/kGBA==,type:str]
    DB_NAME: ENC[AES256_GCM,data:uQOGvHlA37Y=,iv:OzB3OggWQfkmMv92OFvlXr7sg0UVQ9PETg+ZeKXFBQk=,tag:ydw74ePdKiEFnKzjvALoKA==,type:str]
    DB_URL: ENC[AES256_GCM,data:9X8sYj1YfnLb/yEYAJkqQClgu5ucxHyV5kBGu6IKA7Ios6O9Gif92dyAm/IZ67JK777ExGhZjugWF1yrYxs=,iv:cLruKG37xJcsivPVP95N9pjWv0iTCL5UOmqVLv3FPZA=,tag:fdtxC7UpIJ3unMCP+02/oA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150uksj4hjew5ld0rx7u8huclpexecg7hrtf7h8xd8xh4qp58ccns73a0wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdk1FcUgrSHNEQlNUd0kr
            Uk1xMmNCSnhZTjRRWllsSE9Da1RQL2dqMEFNCi8yU3VFYlQvaXN5MFFHaStENEtH
            dHE4OWxLZVpGSnF6TUF3MDdxcTB6UFEKLS0tIFIwVVd1ODhlbmtxaTBvejJrS3Bz
            cDhFUWhheGlXUkwvak9Tbk9wdjUzSEUKKQ8gTuCMw95psAKtkjTz3bg60F1E73g4
            FzOlmVEKvK7UKHz3/GwhdajTgBxp+LgE4fbhfscB9/eGnQo+S8+JEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T15:45:09Z"
    mac: ENC[AES256_GCM,data:0K1/fVciqs52IJbcP+ulrKzBV71FSEWnVeTS5g+iBMfxnmMBDIMQzGZoJUCZsO5Y4g2ccsXl9S+K7ZoxSVvGDYV1AruNb/cfcuJmBU7HuorfgcMOBN9v5ISLLMYRK3qKOrktC8P1QdueRGsdxrjTwjPmVaM1p3tpXLC1kkDOWj8=,iv:yedKyL5vDtKFFfSxCN3rv1KgN3LHdnQ8SkPN1qj9rac=,tag:htVmG3AglNANiQ/ny5LFpQ==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.4
