apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  DB_USER: admin
  DB_PASSWORD: qwerty
  DB_NAME: gosocial
  DB_URL: "postgres://admin:qwerty@postgres:5432/gosocial?sslmode=disable"
