services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-social-api
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: qwerty
      DB_NAME: gosocial
      DB_URL: postgres://admin:qwerty@db:5432/gosocial?sslmode=disable
      REDIS_ENABLED: "true"
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: my-password
      REDIS_DB: 0
      ENV: production
    ports:
      - "8080:8080"

  db:
    image: postgres:16-alpine
    container_name: go-social-db
    restart: always
    environment:
      POSTGRES_DB: gosocial
      POSTGRES_PASSWORD: qwerty
      POSTGRES_USER: admin
    ports:
      - "4566:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: redis-server --save 60 1 --loglevel warning
    environment:
      REDIS_PASSWORD: my-password
      REDIS_PORT: 6379
      REDIS_DATABASES: 16