image:
 repository: registry.gitlab.com/vesselchuckk/gocial
 tag: "3d8dd0da"
 pullPolicy: IfNotPresent

imagePullSecrets:
 - name: gitlab-registry

replicaCount: 1

service:
 type: ClusterIP
 port: 8080
 targetPort: 8080

resources: {}
